name: Build and Release Agent Application

on:
  push:
    tags:
      - 'v*'  # Trigger when a new tag is pushed (for release)
  
  workflow_dispatch:  # Allow manual triggers from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]  # Target OS
        goarch: [amd64, arm64]  # Target architectures

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies and build the application
        run: |
          # Navigate to the agent directory
          cd agent
          
          # Initialize Go modules if needed
          go mod tidy
          
          # Build the Go application
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o agent-${{ matrix.goos }}-${{ matrix.goarch }} ./agent.go

      - name: Create a GitHub Release and Upload Binaries
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}   # Uses the tag that triggered the workflow (e.g., v1.0.0)
          artifacts: |
            agent-linux-amd64
            agent-linux-arm64
          generateReleaseNotes: true
          token: ${{ secrets.GH_TOKEN }}  # Use a PAT or default GITHUB_TOKEN with sufficient permissions

      - name: Upload install/uninstall scripts as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: install-uninstall-scripts
          path: agent/install.sh, agent/uninstall.sh, agent/update.sh
