name: Publish Release

on:
  workflow_dispatch:  # Triggered manually

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up GitHub CLI (for creating releases)
    - name: Set up GitHub CLI
      run: |
        curl -s https://cli.github.com/packages/githubcli-archive.key | sudo tee /etc/apt/trusted.gpg.d/githubcli.asc
        sudo apt update
        sudo apt install gh

    # Step 3: Read version from agent/VERSION.txt
    - name: Read version from agent/VERSION.txt
      id: read_version
      run: |
        VERSION=$(cat agent/VERSION.txt)
        echo "Release version is: $VERSION"
        echo "::set-output name=version::$VERSION"

    # Step 4: Authenticate GitHub CLI
    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    # Step 5: Create a new GitHub release
    - name: Create GitHub Release
      run: |
        gh release create ${{ steps.read_version.outputs.version }} agent/* --title "Release ${{ steps.read_version.outputs.version }}" --notes "Automated release for ${{ steps.read_version.outputs.version }}"

    # Step 6: Upload files to the release (excluding VERSION.txt)
    - name: Upload files to release (excluding VERSION.txt)
      run: |
        # Exclude VERSION.txt and upload other files
        find agent/ -type f ! -name 'VERSION.txt' -exec gh release upload ${{ steps.read_version.outputs.version }} {} --clobber \;
