name: Publish Release

on:
  workflow_dispatch:  # Triggered manually

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up GitHub CLI (for creating releases)
    - name: Set up GitHub CLI
      run: |
        curl -s https://cli.github.com/packages/githubcli-archive.key | sudo tee /etc/apt/trusted.gpg.d/githubcli.asc
        sudo apt update
        sudo apt install gh

    # Step 3: Get version from Git tag or use a custom version (you can modify this part)
    - name: Get release version
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        echo "Release version is: $VERSION"
        echo "::set-output name=version::$VERSION"

    # Step 4: Create a new GitHub release
    - name: Create GitHub Release
      run: |
        gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
        gh release create ${{ steps.get_version.outputs.version }} agent/* --title "Release ${{ steps.get_version.outputs.version }}" --notes "Automated release for ${{ steps.get_version.outputs.version }}"

    # Step 5: Upload files to the release (if additional files need to be attached)
    - name: Upload files to release
      run: |
        gh release upload ${{ steps.get_version.outputs.version }} agent/* --clobber
