name: Publish Release

on:
  workflow_dispatch:  # Triggered manually

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up GitHub CLI (for creating releases)
    - name: Set up GitHub CLI
      run: |
        curl -s https://cli.github.com/packages/githubcli-archive.key | sudo tee /etc/apt/trusted.gpg.d/githubcli.asc
        sudo apt update
        sudo apt install gh

    # Step 3: Read version from agent/VERSION.txt
    - name: Read version from agent/VERSION.txt
      id: read_version
      run: |
        VERSION=$(cat agent/VERSION.txt)
        echo "Release version is: $VERSION"
        echo "::set-output name=version::$VERSION"

    # Step 4: Authenticate GitHub CLI
    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    # Step 5: Create Git tag from the version
    - name: Create Git Tag
      run: |
        VERSION=${{ steps.read_version.outputs.version }}
        git tag -a $VERSION -m "Release $VERSION"
        git push origin $VERSION

    # Step 6: Create a new GitHub release
    - name: Create GitHub Release
      run: |
        VERSION=${{ steps.read_version.outputs.version }}
        gh release create $VERSION agent/* --title "Release $VERSION" --notes "Automated release for $VERSION"

    # Step 7: Upload files to the release (excluding VERSION.txt)
    - name: Upload files to release (excluding VERSION.txt)
      run: |
        VERSION=${{ steps.read_version.outputs.version }}
        # Exclude VERSION.txt and upload other files
        find agent/ -type f ! -name 'VERSION.txt' -exec gh release upload $VERSION {} --clobber \;
